command:
- '/code/remote-script.sh'
org: yuval
project: 5686084218388480
data_volume: 5685154290860032
#data_query: '@version:87e1e5f2ab8facd5f1235a5d147cd6a302c73f29 @seed:1337 @sample:0.3 @split:0.2:0.2:0.6 multi:False AND gtdee:False'
data_query: '@seed:1337 @split:0.2:0.2:0.6 class:"Apple Red 1" OR class:Avocado OR class:Banana OR class:"Cherry 2" OR class:Kiwi OR class:Mango OR class:Nectarine OR class:Pear OR class:Strawberry OR class:Walnut'
data_dest: '/data/$phase/$class'
env:
  DATA_ROOT: /data
  EXPERIMENT_NAME: simple-20e-sgd-5-50-b100
  EPOCHS: 20
  BATCH_SIZE: 100
  OPTIMIZER: sgd
  LEARNING_RATE: 0.01
  MODEL: simple
  SIMPLE_LAYER_DIMENSIONALITY: 50
  SIMPLE_LAYER_COUNT: 5
