command:
- 'python /code/script_iterator.py'
org: yuval
project: 5702926261551104
env:
  EXPERIMENT_NAME: simple-20e-sgd-0-50-lr-0.01
  EPOCHS: 20
  BATCH_SIZE: 10
  MODEL: simple
  SIMPLE_LAYER_DIMENSIONALITY: 50
  SIMPLE_LAYER_COUNT: 0
  OPTIMIZER: sgd
  LEARNING_RATE: 0.01
